import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { getCartProducts } from "../lib/database/model";

export async function getServerSideProps() {
  // Don't forget to await
  const cartData = await getCartProducts("auniquecartid1");
  return {
    props: {
      cartData,
    },
  };
}

export default function Home({ cartData }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <ul>
          {cartData.map((row) => (
            <li key={row.id}>
              {row.name}: {row.price} x {row.quantity} = {row.total_price}{" "}
              (subtotal)
            </li>
          ))}
        </ul>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
